services:
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    networks:
      - golding-network
    restart: unless-stopped
    environment:
      - VITE_API_URL=http://backend:8000

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - golding-network
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:latest
    env_file:
      - .env
    networks:
      - golding-network
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
